site :opscode
cookbook "yum", "~> 3.0.0"
cookbook "yum-epel"
cookbook "yum-repoforge"
cookbook "yum-remi", path: "site-cookbooks/yum-remi"
cookbook "yum-update", path: "site-cookbooks/yum-update"
cookbook "selinux"
cookbook "iptables"
cookbook "git"
cookbook "php"
cookbook "php-wrap", path: "site-cookbooks/php-wrap"
cookbook "composer"
cookbook "apache2"
cookbook "apache2-wrap", path: "site-cookbooks/apache2-wrap"
cookbook "devtools", path: "site-cookbooks/devtools"

